### PR TITLE
Fixed Deadlock in Synchronous Execution

### PR DESCRIPTION
**Pull request by TheInsaneBro**
Fixed deadlock while synchronously read stdout and stderr. (Occurs when using ffmpeg)

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thank you for your contribution.
When does the deadlock occur?
Can you make a test case for that scenario that would fail with old code and work with this one?

**Comment by TheInsaneBro** [comment]
Admittedly, not a very pretty unit test. But I really don't know what's so special about ffmpeg. I couldn't reproduce it otherwise.

**Comment by Tyrrrz** [comment]
Damn. I guess bringing in ffmpeg run-time is going to be a bit of an overkill.
Let's revert the last commit and I'll just merge it as is, without tests.

**Comment by TheInsaneBro** [comment]
I think that's the best for now. If I find out what really goes wrong there I'll ad a unit test later. It's ready to merge now.

Btw I like this project, searched for a long time for such a simple solution to those ugly process handlings.

**Comment by Tyrrrz** [comment]
Merged thank you

**Comment by Nekromancer** [comment]
I think the problem with ffmpeg might be that it's not writing to stdout but to the stderr only

**Comment by Tyrrrz** [comment]
I suspect the problem was that ffmpeg writes progress to console by overwriting the same line on the screen. It probably writes it pretty often which made the buffer hit the size limit and in the older version the streams weren't flushed because of the synchronous locking.

**Pull request merged**
