### PR TITLE
Add username, password and domain to Command builder

### PR DESCRIPTION
**Pull request by MD-V**

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Does this actually work without Shell Execute?

**Comment by MD-V** [comment]
I think it does. I have created a test application with the following code:

`var cmd = Cli.Wrap("ping").WithArguments("127.0.0.1 -t").WithUserName("user2").WithPassword(s);`

Application is started as user1. 
Ping.exe will be started as user2.

The only strange thing that happens is: Ping.exe will be started in a new visible window...

Is this a problem?

**Comment by Tyrrrz** [comment]
Yeah, I think it means it's actually still starting it with shell execute. Can you get the stdout from a process started this way?

**Comment by MD-V** [comment]
Yes the code from your Observe() example code prints the stdout to Console.

**Comment by Tyrrrz** [comment]
Interesting!

Do you have a use case for this feature? Can you tell me more where it's used?

**Comment by MD-V** [comment]
@Tyrrrz I'm trying to explain my use case. I hope it makes sense:

We have a service that is used to backup data. This service runs as a network user on the machine.
We then want to call a script (via CliWrap) from this service that needs a different user to access the users mounted network drives (network drives are user specific).

**Comment by Tyrrrz** [comment]
Thanks! I will merge this and then try to think of some potential design improvements.

**Pull request merged**
