### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by Tyrrrz**
- Changed async workflow to properly cancel without relying on process getting killed
- Simplified sync workflow

### CODE REVIEW

**Comment by Tyrrrz** [comment]
@TheInsaneBro if you have time, can you please take a look and review these changes?
I think the original deadlock issue has been caused by [this](https://blogs.msdn.microsoft.com/oldnewthing/20110707-00/?p=10223). It's also mentioned on MSDN [here](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.standardoutput(v=vs.110).aspx):

> The code example avoids a deadlock condition by calling p.StandardOutput.ReadToEnd before p.WaitForExit. A deadlock condition can result if the parent process calls p.WaitForExit before p.StandardOutput.ReadToEnd and the child process writes enough text to fill the redirected stream. The parent process would wait indefinitely for the child process to exit. The child process would wait indefinitely for the parent to read from the full StandardOutput stream.
There is a similar issue when you read all text from both the standard output and standard error streams.

I tried to simplify the sync workflow a bit while still avoiding the deadlock. Can you check if ffmpeg locks with these changes?

I also changed the async workflow a bit. Previously it was awaiting the `StandardOutput.ReadToEndAsync()` and `StandardError.ReadToEndAsync()` before waiting for process exit. There was a small issue when the task was cancelled via `CancellationToken`, because the stdout/stderr reads were awaited first, the task wouldn't throw until after it finished reading both streams. Because of that, the old workflow heavily relied on actually killing the executing process with `TryKillProcess(process)`. With the new workflow it shouldn't rely on it anymore and shouldn't hang in case the process is not killed for whatever reason.

**Comment by TheInsaneBro** [comment]
Yes, the reworked version is working fine. Do you already know when a new version of the NuGet package is published?

**Comment by Tyrrrz** [comment]
Great!
I'll publish it tomorrow

**Comment by Tyrrrz** [comment]
Pushed the updated nuget package

**Pull request merged**
