### PR TITLE
.NET Standard, .NET 4.7, new NuGet version number

### PR DESCRIPTION
**Pull request by watkinsmatthewp**
Converted CliWrap to .NET standard 2, upgraded CliWrap.Tests to .NET 4.7, and upped the NuGet version number.

This will be helpful so I can use this NuGet package in a .NET Standard project I'm working on, so feel free to push the NuGet package out sooner rather than later :)

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi.
What's the benefit of targeting .net standard 2.0 as opposed to .net45 and .netcore1.0?
Also why didn't you just add `.netstandard2.0` to `<TargetFrameworks>` instead?

**Comment by watkinsmatthewp** [comment]
The project I'm working on is a .NET standard project so it dislikes the NuGet package:

image

**Comment by watkinsmatthewp** [comment]
This pull request is more of a suggestion-- I just like the wrapper you wrote and am happy with whatever targeting pardaigm you want to implement so I can use it :)

**Comment by Tyrrrz** [comment]
Fair enough. For some reason, I didn't think someone would use it inside another library. I'll just add .netstandard2.0 to target frameworks so that it stays compatible with frameworks older than .net47 and .netcore2.0.

**Comment by Tyrrrz** [comment]
Implemented in https://github.com/Tyrrrz/CliWrap/commit/a755de9788eb6677d205e10c8d75cceae3192df1.
New version should be up on nuget within 15 minutes.

**Pull request closed without merging**
