### PR TITLE
Implement graceful cancellation

### LINKED ISSUE #47: Send SIGINT (Ctrl+C) on cancellation
The current cancellation token kills that application which is needed in some cases but it would also be great to have one that could close the application so the application has time to close gracefully and cleanup.  I have a few processes there it would be ideal that i could close them and only kill them as a last resort if the close does not work after a short period of time.

### PR DESCRIPTION
**Pull request by Tyrrrz**
Closes #47

Ignore the massive file moves, the important bits are in `Command.Execution.cs` and `ProcessEx.cs`.

Useful links:

- https://gist.github.com/ycherkes/b216e78ae7ee4418504320f861337ed4
- https://github.com/madelson/MedallionShell/blob/3fddb89860842ffc836a0d0f69b161f67e4aa7c4/MedallionShell/Signals/ProcessSignaler.cs

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Current proposed usage (taken from tests on this branch):

```csharp
[Fact(Timeout = 15000)]
public async Task Command_execution_can_be_canceled_gracefully()
{
    // Arrange
    var stdOutLines = new List<string>();

    using var cts = new CommandCancellationTokenSource();
    cts.CancelGracefullyAfter(TimeSpan.FromSeconds(0.5));

    var cmd = Cli.Wrap("dotnet")
        .WithArguments(a => a
            .Add(Dummy.Program.FilePath)
            .Add("sleep")
            .Add("--duration").Add("00:00:20")
        ) | stdOutLines.Add;

    // Act
    var task = cmd.ExecuteAsync(cts.Token);

    // Assert
    var ex = await Assert.ThrowsAnyAsync<OperationCanceledException>(() => task);
    ProcessEx.IsRunning(task.ProcessId).Should().BeFalse();
    ex.CancellationToken.Should().Be(cts.Token);

    stdOutLines.Should().ContainEquivalentOf("Operation cancelled gracefully.");
    stdOutLines.Should().NotContainEquivalentOf("Done.");
}
```

**Comment by ycherkes** [comment]
Looks awesome to me. 
I just figured out that my code for windows isn't working in unit tests.
So the external executable is required.

**Comment by Tyrrrz** [comment]
@ycherkes 

> I just figured out that my code for windows isn't working in unit tests.
> So the external executable is required.

In your own unit tests or here? Because I haven't implemented it for windows here yet.

As far as I could tell, an external executable is only needed if the process is running in a different console. In practice, that should mostly only happen if the parent process is a GUI application and does not have any console attached, in which case briefly attaching the target console should be painless, I hope. 🤞🏻 

In any case, my design for this feature is that it can silently fail. Even in a situation where SIGINT is passed successfully, the underlying process may still choose to completely disregard it. For that reason, graceful cancellation shouldn't be seen as a guarantee, and it should be "okay" to just do nothing in situations where it's hard to implement (such as this case on Windows with separate console windows).

**Comment by ycherkes** [comment]
> 
> In your own unit tests or here? Because I haven't implemented it for windows here yet.
> 
I put my implementation to your code and got a Timeout exception for all graceful cancellation tests.
Because neither JetBrains, nor MS test adapters doesn't have a Console Window:

   ```
    [DllImport("kernel32.dll")]
    static extern IntPtr GetConsoleWindow();

    [Fact]
    public void CheckConsole()
    {
        var console = GetConsoleWindow();
        console.Should().NotBe(IntPtr.Zero);
    }
```

**Comment by Tyrrrz** [comment]
> > In your own unit tests or here? Because I haven't implemented it for windows here yet.
> 
> I put my implementation to your code and got a Timeout exception for all graceful cancellation tests. Because neither JetBrains, nor MS test adapters don't have a Console Window:
> 
> ```
>  [DllImport("kernel32.dll")]
>  static extern IntPtr GetConsoleWindow();
> 
>  [Fact]
>  public void CheckConsole()
>  {
>      var consolePtr = GetConsoleWindow();
>      // It fails
>      consolePtr.Should().NotBe(IntPtr.Zero);
>  }
> ```
> 
> So the execution flow reaches [this code](https://gist.github.com/ycherkes/b216e78ae7ee4418504320f861337ed4#file-windowsprocessterminator-cs-L77) and CTRL_C doesn't reach the target process.

Ah, makes sense. Would an external process even help here? Since there is no console to attach to.

**Comment by ycherkes** [comment]
Yup, I've verified it. 
Created process still has its own Console, so [MedallionShell.ProcessSignaler](https://github.com/madelson/MedallionShell/tree/master/MedallionShell.ProcessSignaler) works as expected. Also, I tried a similar but c++ based unmanaged exe. Works too.

**Comment by Tyrrrz** [comment]
Decided to drop support for Windows in the initial implementation of this feature. I will look into adding it later in the future, but most likely using a different approach than the one used by MedallionShell, if one exists.

**Pull request merged**
