### PR TITLE
Grand rework

### LINKED ISSUE #24: Use IObserver<T>/IObservable<T> for stdin/stdout/stderr
Title of the issue is self-explanatory: as a suggestion, `stdin` might be more flexibly represented by having **CliWrap** provide an `IObserver<String>` . In this vein, your library would then expose `stdout` and `stderr` as each an instance of the push-oriented interface `IObservable<String>`.

These changes would allow for better integration with other standard techniques, tools, and libraries such as *Reactive Extensions*.

### LINKED ISSUE #25: Support async binary output and input streams
Example of binary pipeline stream:
https://gist.github.com/SlowLogicBoy/45f25b3711c341ba974fe22f04f71f4a
Multiple pipelines example:
https://gist.github.com/SlowLogicBoy/63037d655cf8c667ae09ccebcf1164aa

### LINKED ISSUE #45: IAsyncEnumerable<string> for stdout?
In addition to `SetStandardOutputCallback`, it would be useful to have a method that returns an `IAsyncEnumerable<string>`, to allow us to use `await foreach` to iterate over stdout/stderr as it arrives.

More info in `IAsyncEnumerable`: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream

### PR DESCRIPTION
**Pull request by Tyrrrz**
This is a complete rework of the library. The main idea is that CliWrap now revolves around piping at its core, with all previously available functionality exposed as extensions over that base layer. This rework extends the library with complete support for piping and streaming.

See the tests for some usage examples while this branch is still WIP.

Closes #45
Closes #25
Closes #24

### CODE REVIEW

**Comment by Tyrrrz** [comment]
@glenn-slayden I'm not sure if you're still around, I would be happy if you had time to check out the `ToObservable()` implementation. You can see it in tests [here](https://github.com/Tyrrrz/CliWrap/blob/v3/CliWrap.Tests/StreamingSpecs.cs#L57) and its implementation [here](https://github.com/Tyrrrz/CliWrap/blob/v3/CliWrap/EventStream/CommandEventObservable.cs). Also @Daniel15 too, because I know you were working on creating observables as well.

@Daniel15 you can also check out the async enumerable in action [here](https://github.com/Tyrrrz/CliWrap/blob/v3/CliWrap.Tests/StreamingSpecs.cs#L20).

@SlowLogicBoy you are welcome to check out async binary input/output streams (via piping) [here](https://github.com/Tyrrrz/CliWrap/blob/v3/CliWrap.Tests/PipingSpecs.cs#L70).

Generally, everyone is welcome to leave feedback. I think the branch is in a relatively stable state, so I would expect it to be the future of CliWrap in the coming weeks.

**Comment by Daniel15** [comment]
Thanks @Tyrrrz! I'll try to take a look when I get some free time.

Here's my current CliWrap usage where I tried to handle streaming of output: https://github.com/Daniel15/dnstools/blob/master/src/DnsTools.Worker/Tools/BaseCliTool.cs#L35. My code is kinda sketchy though, so I'm looking forward to something cleaner :)

**Comment by Tyrrrz** [comment]
Edited the second comment to include screenshots of code :)
@Daniel15 thanks, I will take a look. I'm definitely sure it's going to be a lot easier now. I just want to make sure the API is convenient enough because I haven't used IObservable<T> myself at all.

**Comment by Daniel15** [comment]
> I just want to make sure the API is convenient enough because I haven't used IObservable myself at all.

Me neither 😛 

I basically just needed some way of streaming in command-line output and processing it, rather than waiting until the process exits. Some libraries just wait until the end and give you all the output as a string, which is fine for some use cases but not all.

My use case is on https://dnstools.ws/. If you use the "Ping" or "Traceroute" tools, the results stream in from several servers around the world (see https://dnstools.ws/ping/google.com/ as an example). In the backend it's using the `ping` CLI app and parsing the output line by line. It sends five pings, but the results appear as soon as the first ping comes back, rather than waiting for all five to finish.

**Comment by Tyrrrz** [comment]
> I basically just needed some way of streaming in command-line output and processing it, rather than waiting until the process exits. Some libraries just wait until the end and give you all the output as a string, which is fine for some use cases but not all.

Yep, that's how it will work now in one of the execution models (namely observable event stream and async event stream).

**Comment by Daniel15** [comment]
@Tyrrrz Is it possible to publish an alpha package to NuGet (or maybe something like Myget) to make it easier to test? Or is there a dev NuGet repo somewhere?

**Comment by SlowLogicBoy** [comment]
@Tyrrrz LGTM.
I'm only concerned about piping syntax, it might seem "Magic" and not understandable for Beginner - Average C# user.

**Comment by Tyrrrz** [comment]
@Daniel15 I'll try to publish it today.

@SlowLogicBoy thanks. It internally calls `WithStandardInputPipe`/`WithStandardOutputPipe`/`WithStandardErrorPipe` so technically they are optional but they provide much more terser syntax. I think it's fine if it's not very understandable for beginners because it's an advanced feature. I'll try to explain it to the best of my ability in the readme.

The cool thing about piping is that it also supports a variety of different targets, including delegates for example:

```csharp
// Pipe the stdout and stderr into this process' stdout and stderr
var cmd = Cli.Wrap("foo") | (Console.WriteLine, Console.Error.WriteLine);
await cmd.ExecuteAsync();
```

Which is the same as

```csharp
var cmd = Cli.Wrap("foo")
    .WithStandardOutputPipe(PipeTarget.ToDelegate(Console.WriteLine))
    .WithStandardErrorPipe(PipeTarget.ToDelegate(Console.Error.WriteLine));

await cmd.ExecuteAsync();
```

The advantage of using operators gets even more obvious when you pipe multiple commands one into another:

```csharp
var cmd1 = ...;
var cmd2 = ...;
var cmd3 = ...;

var cmd = cmd1 | cmd2 | cmd3;
```

Equivalent to:

```csharp
var cmd = cmd3.WithStandardInputPipe(PipeSource.FromCommand(
                           cmd2.WithStandardInputPipe(PipeSource.FromCommand(
                                    cmd1))));
```

Also note that everything in CliWrap is immutable so by piping you actually create a new command, not modify an existing one (unlike v2), which should make it more sane for the user.

**Comment by Tyrrrz** [comment]
Added readme: https://github.com/Tyrrrz/CliWrap/blob/v3/Readme.md

**Comment by Tyrrrz** [comment]
Published pre-release package: https://www.nuget.org/packages/CliWrap/3.0.0-alpha
It's still a bit buggy but you can try it now.

@Daniel15

**Comment by Tyrrrz** [comment]
I'm not pretty happy with this. Released another pre-release version.
Planning to merge this to master next Thursday, until then it's ready for review. :)

**Comment by Daniel15** [comment]
@Tyrrrz  I was reading [the migration guide](https://github.com/Tyrrrz/CliWrap/wiki/Migration-guide-(from-v2.5-to-v3.0)) and saw this example with async event streams:

```csharp
await foreach (var cmdEvent in Cli.Wrap("cli.exe").ListenAsync())
{
    cmdEvent
        .OnStandardOutput(e => Console.WriteLine($"StdOut> {e.Text}"))
        .OnStandardError(e => Console.WriteLine($"StdErr> {e.Text}"));
}
```

Two pieces of feedback:
1. The `OnStandardOutput` naming makes it sound like it's attaching an event handler, when in reality it looks like it's just doing an `is` check on the `cmdEvent`. Maybe calling it something else would be clearer, like `WhenStandardOutput`?

2. Would it be possible to allow for an async callback? eg
```csharp
cmdEvent.OnStandardOutputAsync(async e => await DoStuffWith(e))
```

I guess I could just do something like:
```csharp
if (x is StandardOutputCommandEvent)
{
	await DoStuffWith(((StandardOutputCommandEvent)x).Text);
}
```

**Comment by Tyrrrz** [comment]
> The OnStandardOutput naming makes it sound like it's attaching an event handler, when in reality it looks like it's just doing an is check on the cmdEvent. Maybe calling it something else would be clearer, like WhenStandardOutput?

Maybe something like `MatchStandardOutput` would work? However that also sounds a bit confusing. These extension methods are only there to avoid manual pattern matching via:

```csharp
switch (cmdEvent)
{
    case StartedCommandEvent started:
        _output.WriteLine($"Process started; ID: {started.ProcessId}");
        break;
    case StandardOutputCommandEvent stdOut:
        _output.WriteLine($"Out> {stdOut.Text}");
        stdOutLinesCount++;
        break;
    case StandardErrorCommandEvent stdErr:
        _output.WriteLine($"Err> {stdErr.Text}");
        stdOutLinesCount++;
        break;
    case ExitedCommandEvent exited:
        _output.WriteLine($"Process exited; Code: {exited.ExitCode}");
        break;
}

or this:

```csharp
if (cmdEvent is StartedCommandEvent started)
{
    _output.WriteLine($"Process started; ID: {started.ProcessId}");
}
else if (cmdEvent is StandardOutputCommandEvent stdOut)
{
    _output.WriteLine($"Out> {stdOut.Text}");
    stdOutLinesCount++;
}
else if (cmdEvent is StandardErrorCommandEvent stdErr)
{
    _output.WriteLine($"Err> {stdErr.Text}");
    stdOutLinesCount++;
}
else if (cmdEvent is ExitedCommandEvent exited)
{
    _output.WriteLine($"Process exited; Code: {exited.ExitCode}");
}
```

Both are a bit verbose but I feel like the confusion and the limitations (like your second point about async) may make it not worth it. Perhaps it's better to remove them?

**Comment by Daniel15** [comment]
I just upgraded to the alpha. Seems to be working well! I'm using `ListenAsync` and the code is a bit cleaner now as I could remove my hacky Reactive method: https://github.com/Daniel15/dnstools/pull/33/files

> Perhaps it's better to remove them?

I think I've come to the same conclusion. Most C# devs should be familiar with pattern matching with `switch` or `if` statements in C# now and so should be OK with just writing a `switch` statement like in your example. That's what I did.

The other possible approach is installing `System.Interactive.Async` (which provides some LINQ operators for async enumerables) and filtering the stream, for example using `OfType` if you **only** want stdout and nothing else:
```csharp
var wrap = Cli.Wrap("foo.exe")
	.ListenAsync(cancellationToken);

await foreach (var stdOut in wrap.OfType<StandardOutputCommandEvent>())
{
	Console.WriteLine(stdOut.Text);
}
```

**Comment by Tyrrrz** [comment]
Updated based on the comments

**Comment by Tyrrrz** [comment]
@Daniel15 pushed another pre-release package with discussed improvements and also a fix to one race condition I found.

**Comment by Daniel15** [comment]
Thanks for completing and merging this - It turned out really well! I'm going to upgrade my app once I get some more free time 😄

**Comment by Tyrrrz** [comment]
Enjoy :)

**Pull request merged**
